use_default_settings: true

general:
  instance_name: "Zalvion Search"

search:
  formats:
    - html
    - json

server:
  secret_key: "7bd6cd6d9a055167c4adfcd2228214c0"
  limiter: false

engines:
  - name: google
    disabled: false
    # Proviamo ad abilitarlo definendo parametri standard per ridurre i blocchi
    categories: general
    shortcut: g

  - name: wikidata
    disabled: true # Lasciamolo disabilitato per ora, evitiamo che blocchi l'avvio

  - name: duckduckgo
    disabled: false
