use_default_settings: true

general:
  instance_name: "Zalvion Search"

search:
  formats:
    - html
    - json

server:
  secret_key: "7bd6cd6d9a055167c4adfcd2228214c0"
  limiter: false

# Aumentiamo il timeout generale a 5.0 secondi per evitare i ConnectTimeout
outgoing:
  request_timeout: 5.0

engines:
  - name: duckduckgo
    engine: duckduckgo
    disabled: false
    # Forza l'uso di una variante diversa se supportata, altrimenti usiamo un fallback

  # Aggiungiamo Brave e Qwant come vie di emergenza: non bloccano Render 
  # e ti daranno la data corretta di oggi (2026)
  - name: brave
    engine: brave
    disabled: false

  - name: qwant
    engine: qwant
    disabled: false

  - name: google
    engine: google
    disabled: true

  - name: wikidata
    engine: wikidata
    disabled: true
